Handlebars.registerPartial('test_result', HandlebarsTemplates['servers/partials/test_result'])
Handlebars.registerPartial('test_request_details', HandlebarsTemplates['servers/partials/test_request_details'])
Handlebars.registerPartial('conformance_metadata', HandlebarsTemplates['servers/conformance_metadata'])
Handlebars.registerPartial('resource_operation', HandlebarsTemplates['servers/resource_operation'])
Handlebars.registerPartial('validation', HandlebarsTemplates['servers/partials/validation'])
Handlebars.registerPartial('suite_result_details', HandlebarsTemplates['servers/partials/suite_result_details'])
Handlebars.registerPartial('suite_select', HandlebarsTemplates['servers/suite_select'])
